parameters:
    malirobot_form_builder.label: "Form Builder Drag&Drop"
    malirobot_form_builder.save_data: true
services:
    malirobot_form_builder.admin:
        class: Malirobot\FormBuilderBundle\Admin\FormBuilderAdmin
        arguments: [~, Malirobot\FormBuilderBundle\Entity\FormBuilder, MalirobotFormBuilderBundle:FormBuilderAdmin, "@service_container"]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: "%malirobot_form_builder.label%" }

    malirobot_form_builder.block:
        class: Malirobot\FormBuilderBundle\Block\FormBuilderBlockService
        arguments:
            - "malirobot_form_builder.block"
            - "@templating"
            - "@service_container"
        tags:
            - {name: "sonata.block"}

    malirobot_form_builder.controller:
        class: Malirobot\FormBuilderBundle\Controller\FormBuilderController
        calls:
            - [setContainer, ["@service_container"]]
